/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "on-tertiary-fixed": "#3e0117",
              "inverse-primary": "#93d697",
              "secondary-container": "#feb234",
              "inverse-surface": "#2e312d",
              "on-surface-variant": "#40493f",
              "on-primary-fixed-variant": "#0c5221",
              "surface-dim": "#d8dbd4",
              "error-container": "#ffdad6",
              "on-primary-container": "#8fd394",
              "secondary-fixed": "#ffddb2",
              "on-secondary-fixed": "#291800",
              "primary-fixed": "#aef3b1",
              "on-error-container": "#93000a",
              "surface-container-high": "#e6e9e2",
              "surface-container-highest": "#e0e3dc",
              "tertiary": "#662035",
              "on-secondary-container": "#6d4700",
              "tertiary-fixed-dim": "#ffb1c1",
              "primary-fixed-dim": "#93d697",
              "surface": "#f8faf3",
              "outline": "#717a6f",
              "primary-container": "#1a5c2a",
              "inverse-on-surface": "#eff2ea",
              "surface-container": "#ecefe7",
              "tertiary-container": "#83374b",
              "on-error": "#ffffff",
              "background": "#f8faf3",
              "on-secondary-fixed-variant": "#624000",
              "on-background": "#191d18",
              "secondary": "#815500",
              "on-tertiary-fixed-variant": "#772e42",
              "on-tertiary": "#ffffff",
              "surface-tint": "#2a6b37",
              "tertiary-fixed": "#ffd9df",
              "on-primary-fixed": "#002108",
              "error": "#ba1a1a",
              "on-primary": "#ffffff",
              "surface-variant": "#e0e3dc",
              "primary": "#004317",
              "outline-variant": "#c0c9bc",
              "on-secondary": "#ffffff",
              "surface-bright": "#f8faf3",
              "surface-container-low": "#f2f5ed",
              "on-tertiary-container": "#ffacbd",
              "surface-container-lowest": "#ffffff",
              "secondary-fixed-dim": "#ffb94c",
              "on-surface": "#191d18"
      },
      "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
      },
      "spacing": {
              "margin-mobile": "16px",
              "gutter": "24px",
              "base": "8px",
              "margin-desktop": "auto",
              "md": "24px",
              "xs": "4px",
              "lg": "48px",
              "max-width": "1200px",
              "sm": "12px",
              "xl": "80px"
      },
      "fontFamily": {
              "label-md": ["Noto Sans", "sans-serif"],
              "headline-lg": ["Noto Sans", "sans-serif"],
              "body-md": ["Noto Sans", "sans-serif"],
              "headline-sm": ["Noto Sans", "sans-serif"],
              "body-lg": ["Noto Sans", "sans-serif"],
              "headline-lg-mobile": ["Noto Sans", "sans-serif"],
              "headline-md": ["Noto Sans", "sans-serif"]
      },
      "fontSize": {
              "label-md": ["14px", {"lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "600"}],
              "headline-lg": ["40px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}],
              "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
              "headline-sm": ["20px", {"lineHeight": "1.4", "fontWeight": "600"}],
              "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
              "headline-lg-mobile": ["32px", {"lineHeight": "1.2", "fontWeight": "700"}],
              "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}]
      }
    },
  },
  plugins: [
    require('@tailwindcss/container-queries'),
    require('@tailwindcss/forms'),
  ],
}
